### PR TITLE
Fixed options passing, since rollup@0.48 options.output is required

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Comment by lemmabit** [comment]
I haven't received any deprecation messages or anything. Is this really needed now? And is that whole weird rigmarole in the code necessary, or can users just change the way they use rollup-stream (disregarding semver, since with #19 there's no more hope of maintaining backwards compatibility anyway)?

Also, please don't mess with my whitespace. I'd appreciate it if you could remove your whitespace-only changes and squash it back into one commit, because I don't want all of that in the history. If you don't, I'll have to do it, which may mean steamrolling your authorship of the commit.

**Comment by Andarist** [comment]
I see you have found the gist about the rollup's API changes :) 

> can users just change the way they use rollup-stream?

It sure is, but it would differ from rollup's and we couldnt use rollup's config files directly and I assume we want to support this.

> Also, please don't mess with my whitespace.

Removed.

**Comment by Andarist** [comment]
@Permutatrix any news on this?

**Comment by lemmabit** [comment]
I see. Rollup's config format has diverged from the JavaScript API. The changes don't seem to have anything to offer to rollup-stream, but you're right that rollup-stream is supposed to support the config format. It's also supposed to support the JavaScript API format, however, so we can't make `output` a required option. I may have to separate it into two functions.

I don't believe I want to implement this support in this way, so I'm going to close the PR. Thanks for submitting it anyway and for changing the whitespace as I asked. I'm going to look into making https://github.com/rollup/rollup/issues/761 a reality.

**Comment by Andarist** [comment]
What is next step? Could I help anyhow? Im using my fork at the moment, but would prefer using official release ;)

**Comment by lemmabit** [comment]
https://github.com/rollup/rollup/issues/761 is what is needed to make support for the config format in tools like rollup-stream feasible, especially if I'm going to take [the tack I intend to](https://github.com/Permutatrix/rollup-stream/issues/19#issuecomment-330696996) with v2.0.0. Rollup has been resistant to the idea in the past, so I think the most helpful thing you can do is show your support for it. I'm going to see about making a pull request. I'll make a comment here if and when I open one.

**Comment by Andarist** [comment]
It would be helpful in bringing attention to the matter if you open new issue on their boards I think.

Do u plan to support old rollup versions? (Even if requested feature is added it obviously wont be available in older rollups)

**Comment by lemmabit** [comment]
> It would be helpful in bringing attention to the matter if you open new issue on their boards I think.

I generally prefer to have one issue per issue. A PR ought to be visible enough.

> Do u plan to support old rollup versions? (Even if requested feature is added it obviously wont be available in older rollups)

I've thought about this... I think people using old Rollups with old config files will just have to use old versions of rollup-stream. It's better than introducing some sort of glue for them right from the start that will have to stay in forever.

**Comment by Andarist** [comment]
Just trolling around - there is no 'working' rollup-stream at the moment for 0.48, 0.49 and 0.50 :troll:

**Comment by lemmabit** [comment]
As long as the config format doesn't change too much by the time 761 gets resolved, the consumer can just jury-rig something. Like this:

```js
var rollup = require('rollup-stream')(Object.assign({}, require('rollup-next'), require('rollup')));
```

All they have to do is have two versions of Rollup installed.

ᕕ( ᐛ )ᕗ

**Pull request closed without merging**
