### PR TITLE
[1.12.0] add cache parameter

### PR DESCRIPTION
**Pull request by skeggse**
This adds the ability to do incremental builds introduced by https://github.com/rollup/rollup/pull/658

### CODE REVIEW

**Comment by Muini** [comment]
This would be great if the pull is accepted, great job @skeggse !

**Comment by lemmabit** [comment]
Alright, yes, this is definitely a necessary feature, and I should have gotten around to addressing the PR a long time ago. Sorry.

Though this is a creative solution, I don't think it's right for rollup-stream. rollup-stream is meant to be as thin a wrapper around Rollup itself as it can be while still exposing as much of Rollup's functionality as makes sense. I would therefore prefer to use something that looks like this:

``` js
var gulp = require('gulp'),
    rollup = require('rollup-stream'),
    source = require('vinyl-source-stream');

var cache;
gulp.task('rollup', function() {
  return rollup({
      entry: './src/main.js',
      cache: cache
    })
    .on('bundle', function(bundle) {
      cache = bundle;
    })
    .pipe(source('app.js'))
    .pipe(gulp.dest('./dist'));
});
```

That would better reflect the package's goal of being just like Rollup, but with streams instead of promises. It would also expose the bundle object directly, allowing users to do more crazy stuff if they wanted to, and I actually think it's more readable this way.

I'll go implement this, I suppose.

**Comment by skeggse** [comment]
sgtm :+1:

**Comment by lemmabit** [comment]
Okay, the new functionality has been published. Sorry it took so long.

**Pull request closed without merging**
